### ISSUE TITLE
fix(DockerBuilder): when doing `RUN` abort after an amount of time?

### ISSUE THREAD

**Issue by nokome** [stencila/dockter#34]
Currently, we wait forever for the `RUN` instruction to finish: https://github.com/stencila/dockter/blob/v0.2.6/src/DockerBuilder.ts#L208

Probably should have some sort of maximum time limit.

**Comment by giorgiosironi** [comment]
Difficult to cover all scenarios, but it can be annoying to have a build being interrupted over an arbitrary (default) time limit; in my experience `RUN` commands map to installations that use the network (downloading packages or resolving a long list of dependencies) and hence can be very slow in some situations due to limited bandwidth.

If `RUN` is being used to run a package manager, it would have its own timeouts that would raise an error and interrupt execution when reached; those can be overridden with the standard primitives of that package manager rather than with an additional Dockter-specific notation.

There is also the possibility of wrapping dangerous instructions in [`timeout` commands](http://man7.org/linux/man-pages/man1/timeout.1.html) which I've seen commonly used, but at runtime more than during build phases.

**Comment by nokome** [comment]
@giorgiosironi: yeah, I think you are right - it would be annoying. This was maybe a kneejerk suggestion to avoid getting stuck in that `while` loop forever. But since most of the time this would be run from the CLI, the user can always press `Ctrl+C`. I'll close this issue.
